#ifndef ATA_DISK_H
#define ATA_DISK_H

#include <stdint.h>

#define ATA_PRIMARY_BUS_BASE                 0x1F0
#define ATA_PRIMARY_DATA_REGISTER_RW         ATA_PRIMARY_BUS_BASE + 0
#define ATA_PRIMARY_ERROR_REGISTER_R         ATA_PRIMARY_BUS_BASE + 1
#define ATA_PRIMARY_FEATURES_REGISTER_W      ATA_PRIMARY_BUS_BASE + 1
#define ATA_PRIMARY_SECTOR_COUNT_REGISTER_RW ATA_PRIMARY_BUS_BASE + 2
#define ATA_PRIMARY_LBA_LOW_REGISTER_RW      ATA_PRIMARY_BUS_BASE + 3
#define ATA_PRIMARY_LBA_MID_REGISTER_RW      ATA_PRIMARY_BUS_BASE + 4
#define ATA_PRIMARY_LBA_HIGH_REGISTER_RW     ATA_PRIMARY_BUS_BASE + 5
#define ATA_PRIMARY_DRIVE_HEAD_REGISTER_RW   ATA_PRIMARY_BUS_BASE + 6
#define ATA_PRIMARY_STATUS_REGISTER_R        ATA_PRIMARY_BUS_BASE + 7
#define ATA_PRIMARY_COMMAND_REGISTER_W       ATA_PRIMARY_BUS_BASE + 7

#define ATA_READ_PRIMARY_STATUS_R inb(ATA_PRIMARY_STATUS_REGISTER_R)
#define ATA_READ_PRIMARY_ERROR_R  inb(ATA_PRIMARY_ERROR_REGISTER_R)

#define ATA_PRIMARY_CONTROL_BASE                      0x3F6
#define ATA_PRIMARY_CONTROL_ALT_STATUS_REGISTER_R     ATA_PRIMARY_CONTROL_BASE + 0
#define ATA_PRIMARY_CONTROL_DEVICE_CONTROL_REGISTER_W ATA_PRIMARY_CONTROL_BASE + 0
#define ATA_PRIMARY_CONTROL_DRIVE_ADDRESS_REGISTER_W  ATA_PRIMARY_CONTROL_BASE + 1

#define ATA_SECONDARY_BUS_BASE                 0x170
#define ATA_SECONDARY_DATA_REGISTER_RW         ATA_SECONDARY_BUS_BASE + 0
#define ATA_SECONDARY_ERROR_REGISTER_R         ATA_SECONDARY_BUS_BASE + 1
#define ATA_SECONDARY_FEATURES_REGISTER_W      ATA_SECONDARY_BUS_BASE + 1
#define ATA_SECONDARY_SECTOR_COUNT_REGISTER_RW ATA_SECONDARY_BUS_BASE + 2
#define ATA_SECONDARY_LBA_LOW_REGISTER_RW      ATA_SECONDARY_BUS_BASE + 3
#define ATA_SECONDARY_LBA_MID_REGISTER_RW      ATA_SECONDARY_BUS_BASE + 4
#define ATA_SECONDARY_LBA_HIGH_REGISTER_RW     ATA_SECONDARY_BUS_BASE + 5
#define ATA_SECONDARY_DRIVE_HEAD_REGISTER_RW   ATA_SECONDARY_BUS_BASE + 6
#define ATA_SECONDARY_STATUS_REGISTER_R        ATA_SECONDARY_BUS_BASE + 7
#define ATA_SECONDARY_COMMAND_HEAD_REGISTER_W  ATA_SECONDARY_BUS_BASE + 7

#define ATA_SECONDARY_CONTROL_BASE                      0x376
#define ATA_SECONDARY_CONTROL_ALT_STATUS_REGISTER_R     ATA_SECONDARY_CONTROL_BASE + 0
#define ATA_SECONDARY_CONTROL_DEVICE_CONTROL_REGISTER_W ATA_SECONDARY_CONTROL_BASE + 0
#define ATA_SECONDARY_CONTROL_DRIVE_ADDRESS_REGISTER_W  ATA_SECONDARY_CONTROL_BASE + 1

#define ATA_SECTOR_SIZE 512

#define ATA_WRITE_WAIT() \
    __asm__ volatile("jmp 1f\n1:");

void ata_wait_bsy(void);
int ata_wait_drq(void);
uint8_t ata_get_error(void);
int ata_identify(uint16_t *buf);
void ata_read(uint32_t lba, uint8_t sectors_count, uint16_t *buf); // 16 bits for buf since data port for ATA PIO is limited to 2 bytes per read from sector in drive buffer
void ata_write(uint32_t lba, uint8_t count, uint16_t *buf);

#endif //ATA_DISK_H
